### PR TITLE
bookmarklet link dynamically generated

### PR DESCRIPTION
**Pull request by cdelahousse**

### CODE REVIEW

**Comment by psimonyi** [comment]
Uh, are you missing a file? I don't see the code to generate the link anywhere.

**Comment by psimonyi** [comment]
... or I'm blind, or the page hadn't finished loading.

**Comment by psimonyi** [comment]
Should this be an inline script? Maybe it would be cleaner as a separate file. I'm not sure; does anyone else have an opinion?

**Comment by cdelahousse** [comment]
I figured if was nicer to keep it all together.

All the script files were nice and encapsulated and I didn't want to add another $(document).ready() function.

**Comment by psimonyi** [comment]
Okay, sure. Seems fine for now, anyway.

**Pull request merged**
