### PR TITLE
windows.location.origin is not supported by FF

### PR DESCRIPTION
**Pull request by cdelahousse**
Fucking Simon and the hilarity he sees in my honest observations!!!!

### CODE REVIEW

**Comment by psimonyi** [comment]
Firefox 21 supports it.
https://developer.mozilla.org/en-US/docs/DOM/window.location

**Comment by spratt** [comment]
@psimonyi We discovered that.  But that it is supported in the next version of FF is not a good reason to use it.

**Comment by bheesham** [comment]
lol

**Comment by spratt** [comment]
Screen Shot 2013-04-12 at 3 04 52 PM

**Pull request merged**
